project:
  type: website

website:
  title: " "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: training.qmd
        text: Training        
      - href: talks.qmd
        text: Talks
      - href: blog.qmd
        text: Blog
      - icon: github
        href: https://github.com/vivekjason
      - icon: twitter
        href: https://twitter.com/vivekjason87
format:
  html:
    theme: litera
    css: styles.css

editor: visual

execute:
  freeze: auto

resources:
  - CNAME