project:
  type: website

website:
  title: "Vivek Jason Jayaraj"
  favicon: images/vivekjason2.png
  navbar:
    logo: ""
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: training.qmd
        text: Training
      - href: talks.qmd
        text: Talks
      - href: writing.qmd
        text: Writing
      - href: cv.qmd
        text: CV
      - icon: github
        href: https://github.com/vivekjason
      - icon: twitter-x
        href: https://twitter.com/vivekjason1987
  page-footer:
    left: "© 2026 Vivek Jason Jayaraj · built with Quarto"
    right:
      - icon: github
        href: https://github.com/vivekjason
      - icon: linkedin
        href: https://www.linkedin.com/in/vivek-jason-jayaraj-605a09139/
      - icon: twitter-x
        href: https://twitter.com/vivekjason1987
      - icon: envelope
        href: mailto:vivekjason1987@gmail.com

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

resources:
  - CNAME
  - cv/cv_vivekjasonjayaraj_260721.docx
