---
title: "Projects"
pagetitle: "Projects — Vivek Jason Jayaraj"
editor: visual
format:
    html:
        toc: true
        toc-depth: 3
---

-   **Automated Public Health Reports**

    Lead Analyst · from November 2025

-   **Precision Public Health for NCD Risk Profiling** (in collaboration with Google)

    Lead Analyst · from January 2025

-   **Human Resource Optimisation Project**

    Ministry of Health Malaysia · Lead Analyst · from August 2024

-   **Real-World Effectiveness of COVID-19 Vaccines under the Malaysian National Immunisation Programme (RECoVaM)**

    National Institutes of Health, Universiti Malaya · Research Lead and Analyst · 2022 – 2025

-   **Optimisation of Peka B40 & NHSI for Non-communicable Disease Screening**

    ProtectHealth Sdn Bhd, Biostatistics and Data Repository Sector (NIH) · Research Lead and Analyst · from September 2023

-   **Colorectal Pathways Project: a precision public health approach to optimising colorectal screening**

    Institute for Health Systems Research, Biostatistics and Data Repository Centre (NIH), Disease Control Division (MOH) · Analyst · from May 2023

-   **Automation of ICD-10 coding using a Natural Language Processing approach for death registration data**

    Biostatistics and Data Repository Sector (NIH), Institute for Public Health (NIH) · Analyst · 2022 – 2024

-   **Machine learning for the profiling of undiagnosed diabetes, hypertension and cholesterolaemia**

    Biostatistics and Data Repository Sector (NIH), Institute for Public Health (NIH) · Research Lead and Analyst · 2022 – 2023

-   **Modelling the cervical cancer screening programmes in Malaysia**

    Institute for Health Systems Research (NIH) · Consultant · September 2023

-   **COVID-19 Country Report 2023**

    National Institutes of Health · Analyst · 2023

-   **COVID-19 Epidemiological Analysis and Strategies (CEASe)**

    Universiti Malaya · Analyst · March 2020 – January 2023
